apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: olbc0pug8-go
  janus-idp.io/tekton: olbc0pug8-go
  backstage.io/kubernetes-id: olbc0pug8-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: olbc0pug8-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
